### PR TITLE
Add MacOS support

### PR DESCRIPTION
**Pull request by mbarnach**
Refactor code to make it works as an autonomous framework.
Add the MacOS support.
Add a new example to using MacOS testing.

### CODE REVIEW

**Review by leandromperez — CHANGES_REQUESTED** [review]
Hi Mathieu,
Thanks for creating this PR! it will be great to have MacOS support.
I think before merging your PR, it would be nice to get rid of several of those if statements using an approach similar to this one:
https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/ViewController.swift

With that, we would just reference ViewController, and it wouldn't mind if it was NS or UI...

Any thoughts on that?

**Comment by mbarnach** [comment]
The interfaces are slightly different:
 * on iOS, you create a storyboard with a string name whereas on MacOS it is with a Storyboard.Name structure
 * the method calls on iOS is `instantiateInitialViewController` whereas on MacOS it is `instantiateInitialController`

I think we may be able to get rid of some include of UIKit as we are for AppKit (to be confirmed).

**Comment by leandromperez** [comment]
Hi @mbarnach 
I just saw your chances. It looks much better!
One thing I noticed is that there is no target and schemes for running in MacOS, did you create those in your machine? 
I think that'll be necessary to try it out right?
Thanks for your good work!

**Comment by mbarnach** [comment]
Is the Podfile not creating them?
I'm only using the testing of the target, I never run it explicitly.

**Comment by leandromperez** [comment]
No, it's not creating them, the target needs to be in the example project in order to run mac os tests.

I think you need to:

1. Create a target in the project, name it 'Tests MacOS' for example.

2. Add this to the Podfile of the example:
target 'Tests MacOS' do
    platform :osx, '10.11'
    use_frameworks!

    pod 'SpecLeaks', :path => '../'

    inherit! :search_paths
    pod 'RxSwift'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'RxCocoa'
end


3. I couldn't run it because there was a compiler error with 
specleaks/Example/Pods/RxCocoa/RxCocoa/Deprecated.swift:235:48: Use of undeclared type 'RxTextFieldDelegateProxy'

I don't have time to dig into it today..

**Comment by leandromperez** [comment]
@mbarnach 
It looks like there were 2 compile errors in RxSwift/RxCocoa for macOS:

https://github.com/ReactiveX/RxSwift/issues/1142

I just fixed that and added SwiftLint too. 

You can run the macOS tests now, some are failing because loading the storyboard for macOS is not working, I will take a look at it when I can.

**Comment by mbarnach** [comment]
Great! Thanks it works for me.

**Pull request merged**
