### PR TITLE
0.1.6 Feature: Carthage example project

### PR DESCRIPTION
**Pull request by leandromperez**

### CODE REVIEW

**Comment by serahug** [comment]
Hello @leandromperez,
Using Carthage, 0.1.5 works great, but not 0.1.6 (who fails to compile)
Could you take a look ?

Carthage log :
/Users/XXXXX/Downloads/specleaks-master/Carthage-Example/Carthage/Checkouts/specleaks/Carthage-Example/Carthage/Checkouts/specleaks/SpecLeaks/Classes/Expectation+Leaks.swift:10:8: error: no such module 'Nimble'

**Comment by leandromperez** [comment]
hi @Serahug how are you testing it? I mean the carthage usage..?

**Comment by serahug** [comment]
Hi, I clone the project, "carthage bootstrap" works fine (specleaks 1.0.5). Then I update the dependency to 1.0.6 using "carthage update --platform iOS --cache-builds" and the (carthage) build fails

**Comment by leandromperez** [comment]
@Serahug I think it might be the quick version, I'd changed it to 2.1.0. I just published 0.1.7, which has 2.0.0 again, could you please check?

**Comment by josueruiz7** [comment]
@leandromperez the problem here is that you pushed the files on the directory  `Carthage-Example/Carthage/` (it is a cache, no need to push it) so the frameworks inside the cache are being build in the client side, that's why it seems is being building twice:
```
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "SpecLeaks" in SpecLeaks.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "SpecLeaks" in SpecLeaks.xcodeproj
```
and generates the crash

```
Build Failed
	Task failed with exit code 65
```

So you should Ignore that directory (adding that directory to the .gitignore file), I tested it and it works

**Comment by leandromperez** [comment]
@josueruiz7 oh gotcha, thanks! I'll update asap

**Pull request merged**
